stages:
  - codeCoverage
  
buildAndUnitTesting:
  image: openjdk:8-jdk
  stage: build
  script:
    - chmod +x gradlew
    - ./gradlew build
    
codeCoverage:
  image: openjdk:8-jdk
  stage: codeCoverage
  script:
    - chmod +x gradlew
    - ./gradlew test jacocoTestReport