stages:
  - deployContract

deploy_dev:
  stage: deployContract
  image: ruby:2.3
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=orcha-prepare-order --api-key=$HEROKU_API_KEY # HEROKU_API_KEY set into gitlab https://gitlab.com/BenOrcha/orcha/settings/ci_cd 
  environment:
    name: dev
    url: https://orcha-prepare-order.herokuapp.com


   