stages:
  - build
  - codeCoverage
  - compileContract
  
buildAndUnitTesting:
  image: openjdk:8-jdk
  stage: build
  script:
    - chmod +x gradlew
    - ./gradlew build
    
codeCoverage:
  image: openjdk:8-jdk
  stage: codeCoverage
  script:
    - chmod +x gradlew
    - ./gradlew test jacocoTestReport
    
compileContract:
  image: openjdk:8-jdk
  stage: compileContract
  script:
    - chmod +x gradlew
    - ./gradlew compileOrcha -PorchaFile="['restWebService/RestWebService.groovy']"