stages:
  - build
  - codeCoverage
  
buildAndUnitTesting:
  stage: build
  script:
    - chmod +x gradlew
    - ./gradlew build
    
codeCoverage:
  stage: codeCoverage
  script:
    - ./gradlew test jacocoTestReport