package orcha.langimport groovy.util.logging.Slf4j;import orcha.lang.compiler.referenceimpl.xmlgenerator.impl.ErrorUnwrapper;import orcha.lang.configuration.EventHandler;import orcha.lang.configuration.OrchaSessionimport org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.SpringApplicationimport org.springframework.boot.autoconfigure.EnableAutoConfiguration;import org.springframework.cloud.stream.annotation.EnableBindingimport org.springframework.cloud.stream.annotation.StreamListenerimport org.springframework.context.ApplicationContextimport org.springframework.context.annotation.AnnotationConfigApplicationContextimport org.springframework.context.annotation.Bean;import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.ImportResourceimport org.springframework.core.env.AbstractEnvironmentimport org.springframework.cloud.stream.messaging.Sink
/** *  * Orcha xml spring context are loaded dynamically from the auo generated class ImportDynamicResources *  * @author Ben C. * */
@Configuration
@EnableAutoConfiguration
@ComponentScan(basePackages=["configuration","generated"])@EnableBinding(Sink.class)@Slf4j
class OrchaSpringIntegrationLauncher{ // extends ImportDynamicResourcesForConfiguration{					@Autowired	ApplicationContext context		@StreamListener(Sink.INPUT)	public void handle(service.prepareOrder.Order order) {		System.out.println("Received: " + order);		Cafe gateway = context.getBean(Cafe.class)		gateway.placeOrder(order)	}	/*	public static class Person {		private String name;		public String getName() {			return name;		}		public void setName(String name) {			this.name = name;		}		public String toString() {			return this.name;		}	}*/		@Bean	OrchaSession orchaSession(){		return new OrchaSession()	}		public static void main(String[] args) {		try{			System.setProperty(AbstractEnvironment.ACTIVE_PROFILES_PROPERTY_NAME, "default");	// restoring the String http default port to 8080 (application.properties)			SpringApplication application = new SpringApplication(OrchaSpringIntegrationLauncher.class)			application.run(args)		} catch(org.springframework.beans.factory.BeanCreationException e){			log.error("Configuration error into the configuration file: " + e.getRootCause(), e)		} catch(org.springframework.integration.transformer.MessageTransformationException e){			log.error(e.getLocalizedMessage(), e)		}			}

}
