
package orcha.lang.configure;



/**
 * Do not edit this file : auto generated file
 * 
 */
@org.springframework.boot.context.properties.ConfigurationProperties(prefix = "driving")
public class ConfigurationProperties {


}
