
package orcha.lang.configure;



/**
 * Do not edit this file : auto generated file
 * 
 */
@org.springframework.boot.context.properties.ConfigurationProperties(prefix = "driving")
public class ConfigurationProperties {

    public ConfigurationProperties.QueueOutputFile queueOutputFile = new QueueOutputFile();

    public ConfigurationProperties.QueueOutputFile getQueueOutputFile() {
        return queueOutputFile;
    }

    public void setQueueOutputFile(ConfigurationProperties.QueueOutputFile queueOutputFile) {
        this.queueOutputFile = queueOutputFile;
    }

    public class QueueOutputFile {

        public String directory;
        public String filename;

        public String getDirectory() {
            return directory;
        }

        public void setDirectory(String directory) {
            this.directory = directory;
        }

        public String getFilename() {
            return filename;
        }

        public void setFilename(String filename) {
            this.filename = filename;
        }

    }

}
