
package orcha.lang.configure;



/**
 * Do not edit this file : auto generated file
 * 
 */
@org.springframework.boot.context.properties.ConfigurationProperties(prefix = "driving")
public class ConfigurationProperties {

    public ConfigurationProperties.EventSourcingOutputFile eventSourcingOutputFile = new EventSourcingOutputFile();

    public ConfigurationProperties.EventSourcingOutputFile getEventSourcingOutputFile() {
        return eventSourcingOutputFile;
    }

    public void setEventSourcingOutputFile(ConfigurationProperties.EventSourcingOutputFile eventSourcingOutputFile) {
        this.eventSourcingOutputFile = eventSourcingOutputFile;
    }

    public class EventSourcingOutputFile {

        public String directory;
        public String filename;

        public String getDirectory() {
            return directory;
        }

        public void setDirectory(String directory) {
            this.directory = directory;
        }

        public String getFilename() {
            return filename;
        }

        public void setFilename(String filename) {
            this.filename = filename;
        }

    }

}
