
package orcha.lang;

import orcha.lang.compiler.referenceimpl.configurationproperties.ConfigurationPropertiesGenerator;
import orcha.lang.configuration.OrchaSession;

import org.springframework.boot.autoconfigure.ImportAutoConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.ImportResource;


/**
 * Do not edit this file : auto generated file
 * 
 */
@Configuration
//@ImportAutoConfiguration(org.springframework.cloud.stream.test.binder.TestSupportBinderAutoConfiguration.class)
@ComponentScan(basePackages = {
    "configuration",
    "generated"
})
@ImportResource({
    "classpath:/Orcha partitioning.xml",
    "classpath:/Orcha partitioningQoS.xml"
})
public class ImportDynamicResourcesForTestConfiguration {


    @Bean
    public OrchaSession orchaSession() {
        OrchaSession orchaSession = new OrchaSession();
        return orchaSession;
    }
    
    @Bean
	ConfigurationPropertiesGenerator configurationPropertiesGenerator(){
		return new ConfigurationPropertiesGenerator();
	}

}
