
package orcha.lang;

import org.springframework.context.annotation.ImportResource;


/**
 * Do not edit this file : auto generated file
 * 
 */
@ImportResource({
    "classpath:/bank service.xml",
    "classpath:/bank serviceQoS.xml"
})
public class ImportDynamicResourcesForConfiguration {


}
