
package orcha.lang;

import org.springframework.context.annotation.ImportResource;


/**
 * Do not edit this file : auto generated file
 * 
 */
@ImportResource({
    "benchmarking services.xml",
    "benchmarking servicesQoS.xml"
})
public class ImportDynamicResourcesForConfiguration {


}
