
package orcha.lang;

import org.springframework.context.annotation.ImportResource;


/**
 * Do not edit this file : auto generated file
 * 
 */
@ImportResource({
    "order over http.xml",
    "order over httpQoS.xml"
})
public class ImportDynamicResourcesForConfiguration {


}
